version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    env_file:
      - ./config/.env.dev
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication
  web:
    image: studaid/auth-service
    ports:
      - 4000:4000
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      
    command: ["./wait-for-it.sh", "db:5432", "redis:5432", "--", "npm", "run", "start:dev"]

networks:
  webnet:

